server:
  port: 8081

eureka:
  client:
    registerWith-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
    
spring:
  cloud:
    config:
      uri:
      - http://${CONFIG_SERVER:localhost}:8888/
  jpa:    show-sql: true
    hibernate:      ddl-auto: none
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:user}
    username: ${RDS_USERNAME:user}
    password: ${RDS_PASSWORD:dummyuser}  

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
logging:
  level:
    com:
      logixal: debug
      
management:
  endpoints:
    web:
      exposure:
        include: "*"